### ISSUE TITLE
膜拜大佬，要是能加上自动答题或者加上多线程刷课进一步提高效率就更好了

### ISSUE THREAD

**Issue by jadechjin** [luoyanpei/-JSU-#1]

**Comment by luoyanpei** [comment]
自动刷题我看过了，之前是有BUG的但是现在BUG修复了，保密性已经加强了，雨课堂的科目在CSDN上搜都能搜到全部的答案，至于文字探讨题目，都是使用chatgpt生成的。至于你说的多线程刷课，你完全可以多开几个脚本一起刷，或者直接挂着刷就行了。有任何问题还可以联系我。

**Comment by jadechjin** [comment]
你的意思是开多个脚本刷不同的课吗？如果我想开脚本刷同一课程的不同章节呢（手动狗头）

**Comment by luoyanpei** [comment]
你可以改一下哈，我本身不是计算机专业的，对这些也不是很懂。期待你的改进;D


0xAA55
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luoyanpei/-JSU-"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 晚上9:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [luoyanpei/-JSU-] 膜拜大佬，要是能加上自动答题或者加上多线程刷课进一步提高效率就更好了 (Issue #1)





 
你的意思是开多个脚本刷不同的课吗？如果我想开脚本刷同一课程的不同章节呢（手动狗头）

**Comment by jadechjin** [comment]
我也不是计算机专业的哈哈哈，小白一个
